baseURL = "https://arcaravaggi.github.io/"
languageCode = "en-us"
theme = "PaperMod"
publishDir = "docs"

relativeURLs = false
canonifyURLs = true




[markup.goldmark.renderer]
unsafe = true

[[params.socialIcons]]
name = "University Staff Profile"
url = "https://pure.southwales.ac.uk/en/persons/anthony-caravaggi/"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/arcaravaggi"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/arcaravaggi/"

[[params.socialIcons]]
name = "ResearchGate"
url = "https://www.researchgate.net/profile/Anthony-Caravaggi"

[[params.socialIcons]]
name = "BlueSky"
url = "https://bsky.app/profile/thonoir.bsky.social"

#[[params.socialIcons]]
#name = "Soundcloud"
#url = "https://linkedin.com/in/yourusername"

[params.profileMode]
enabled = true
title = "Dr Anthony Caravaggi"
subtitle = "Conservation biologist at the University of South Wales"
imageUrl = "img/profile.jpg"
imageTitle = "Profile Photo"


[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  hero = true
  customCSS = ["css/custom.css"]
  showNewSection = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "About"
#url = "/about/"
#weight = 2

[[menu.main]]
name = "R for Nervous Humans"
url = "/r-for-nervous-humans/"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4

#[[menu.main]]
#name = "Teaching"
#url = "/teaching/"
#weight = 5

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 7